### ISSUE TITLE
Rename ubqt to ubnt

### ISSUE THREAD

**Issue by jinjirosan** [fwijnholds/ta-ubiquiti-support#3]
First of all , awesome TA. Please consider renaming your references on UBQT to UBNT which is the official abbreviation for Ubiquiti Networks. No biggie, just that my OCD really appreciates this :-)

**Comment by fwijnholds** [comment]
Will have to check with the install-base. Sourcetype name changes might break their dashboards.

**Comment by fwijnholds** [comment]
Done, and testing. Update will be posted soon

**Comment by jinjirosan** [comment]
Awesome, good stuff. UBNT or UniFi could both work.
