### ISSUE TITLE
Clarification needed on Method 1 Install

### ISSUE THREAD

**Issue by skenigma** [fwijnholds/ta-ubiquiti-support#6]
Your instructions state 
`Download and install the ubqt_indexes.spl "https://github.com/fwijnholds/ta-ubiquiti-support/blob/master/org_all_indexes.spl"`
However there is no clarification as to where/how to.

**Comment by fwijnholds** [comment]
Hey Scott, thanks for raising this. Indexes live on your indexers, I assumed that is common knowledge. I added this to the documentation.

**Comment by x99percent** [comment]
> Indexes live on your indexers

For further clarity for anyone else finding this, you install the .spl file in the "Manage Apps" section, select "Install app from file", and pick this .spl file.
