### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by poiromaniax** [fwijnholds/ta-ubiquiti-support#7]
Hey,

Thanks for creating this.

I'm a little confused with the instructions though:

1) ta-ubiquiti/local did not exist. I had to manually create /local. Is this correct?
2) I installed the org_all_indexes.spl through the web interface under "Add apps"?
3) When configuring data source - do I choose Search & Reporting app or org_all_indexes?
4) Sourcetype - I can choose any and it will parse all the data?
5) What does the TA-Ubiquiti app actually do? Theres nothing on the dash.....

Right now events are coming in, but they are messy with no meaning (e.g) :

`Mar 12 15:31:57 192.168.0.1 Mar 12 15:31:57 Router kernel: ll header: 00000000: f0 9f c2 11 47 95 00 12 d9 54 1f e7 08 00        ....G....T....`

Thanks!

**Comment by fwijnholds** [comment]
Hi Poiromaniax; 

Thanks for reaching out! See my answers inline:

1. ta-ubiquiti/local did not exist. I had to manually create /local. Is this correct?

Yes, default is what ships with Splunk Apps, this is overwritten when you install an update to the app. Local should contain your changes/config.

2. I installed the org_all_indexes.spl through the web interface under "Add apps"?
There are many ways of installing an app; add app is one way others can be found here: 
https://docs.splunk.com/Documentation/AddOns/released/Overview/Singleserverinstall

3. When configuring data source - do I choose Search & Reporting app or org_all_indexes?
The Search & Reporting app is a good choice! 

4. Sourcetype - I can choose any and it will parse all the data?
You should chose ubnt as a default sourcetype. 

5. What does the TA-Ubiquiti app actually do? Theres nothing on the dash.....
This is a Technical add-on, which does the field extractions in a CIM compliant fashion. 

Hope this helps,
Filip

**Comment by poiromaniax** [comment]
Thanks for the reply!

FYI, I had to copy the info from the transforms.conf and props.conf on the server itself and not the ones found here on Github. The Github ones are lacking almost all the content.....

**Comment by fwijnholds** [comment]
Yes the props & transforms on this site are just here as an example. When I have some time I will improve the docs. Thanks for the feedback!

**Comment by fwijnholds** [comment]
Hi Poiromaniax, 

The local editions do not need all the content which are shipped with the TA, just the changes! 
Splunk will load both the local and default files. You might actually run into issues this way; as I make updates to the Add-On, new extractions and bugfixes will go to the props.conf. When Splunk sees an entry in local for a specific sourcetype, this will take presedence over what is in default., and hence you might miss out on fixes and improvements. 

HTH.

**Comment by fwijnholds** [comment]
I think this issue has been solved now? Please reopen if this is not the case.
