### ISSUE TITLE
Edgerouter? 

### ISSUE THREAD

**Issue by rtmgllc** [fwijnholds/ta-ubiquiti-support#8]
I have an Edgerouter 10X, will this TA work for that? Or only USG?

**Comment by fwijnholds** [comment]
Hi Rtmgllc, I have not tested with the edge router as I don’t have access to such a device. If you can send me a sample of the logs I can add field extractions to this TA.

**Comment by rtmgllc** [comment]
Sorry for the delay! I will send them over later today!

**Comment by fwijnholds** [comment]
Any news on this?

**Comment by rtmgllc** [comment]
Sorry, I ended up getting really busy with work. I will get an example for you this week.

**Comment by fwijnholds** [comment]
No worries :) just checking

**Comment by rtmgllc** [comment]
The logging engine on my edgerouter is giving me some issues, I will try to get some examples up soon.

**Comment by rtmgllc** [comment]
Here is what the logging looks like (I didn;t blot out IP's since they are not unique to my network):

TCP Example:
[WAN_OUT-20-D]IN=switch0 OUT=eth0 MAC=18:e8:29:bf:ba:df:9c:8e:cd:0d:be:e3:08:00 SRC=10.0.0.61 DST=34.227.6.54 LEN=60 TOS=0x00 PREC=0x00 TTL=63 ID=37487 DF PROTO=TCP SPT=41997 DPT=12367 WINDOW=14600 RES=0x00 SYN URGP=0

UDP Example:
[WAN_OUT-20-D]IN=switch0 OUT=eth0 MAC=18:e8:29:bf:ba:df:4c:11:bf:f5:4f:0a:08:00 SRC=10.0.0.71 DST=34.238.41.119 LEN=59 TOS=0x00 PREC=0x00 TTL=63 ID=3877 DF PROTO=UDP SPT=23048 DPT=8800 LEN=39

The stuff in the [] is the rule name, its -D for "drop" and -A for "accept". 

The examples above are logs when stuff is dropped, when its accepted it looks the same, but the name has a -A in it, like the UDP rule below...

[WAN_OUT-default-A]IN=switch0 OUT=eth0 MAC=18:e8:29:bf:ba:df:52:54:00:bb:5e:42:08:00 SRC=10.0.0.57 DST=149.112.112.112 LEN=52 TOS=0x00 PREC=0x00 TTL=63 ID=23415 DF PROTO=TCP SPT=45586 DPT=853 WINDOW=342 RES=0x00 ACK FIN URGP=0

**Comment by rtmgllc** [comment]
I am going to setup syslog, which is how these would get sent to Splunk. I am not sure if syslog will change up the logs I sent above. I will test that this weekend and let you know.

**Comment by mrprobz** [comment]
Hi @fwijnholds You have a unifygateway right? I'm trying to get the statistics from the gateway into splunk as a dashboard. Unfortunately no app exists like for fortigate.. Reading in the syslog data is a bit difficult to sense from it to pull out usefull stuff..
Have you ever tried this?

**Comment by fwijnholds** [comment]
Hi @mrprobz the syslog data from the USG is really poor in this area.  What are you looking for exactly?

**Comment by mrprobz** [comment]
Hi @fwijnholds i was trying to map incoming dropped connection or "blocked" connections coming from the USG. 
I created the fw rules for this to create the logs and then capture it on syslog.

I see similar logs like this = Message: [WAN_LOCAL-4000-D]IN=eth0 OUT= MAC=fc:ec:da:05:bd:87:00:17:10:87:ad:5c:08:00 SRC=195.54.161.125 DST=XX.XX.xx.XX LEN=40 TOS=0x00 PREC=0x00 TTL=243 ID=37849 PROTO=TCP SPT=44317 DPT=14051 WINDOW=1024 RES=0x00 SYN URGP=0 

But when i forward my logs directly to splunk it doesnt see these kind of logs..

**Comment by fwijnholds** [comment]
Hi @mrprobz,

The TA has the extraction to figure out what the blocked or allowed is. It is actually the letter at the end of the rule. ie. [WAN_LOCAL-4000-D] the D indicates the event was blocked. 

I am closing the issue, as the initial issue might be solved?
